[package]
name = "what-a-peak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_http = "0.7"
mediawiki = "0.2.8"
rand = "0.8.5"
serde_json = "*"
tokio = { version = "1", features = ["full"] }
